"""Generator entrypoint.

    python -m careweave.data.generator.run --members 2000

Writes Parquet for structured tables and JSONL for events and documents. The
seed is fixed in config, so the dataset is byte-reproducible.
"""

from __future__ import annotations

import argparse
import json
import random
from dataclasses import asdict
from datetime import date, datetime
from pathlib import Path
from typing import Any, Iterable

import pandas as pd
from pydantic import BaseModel

from careweave.config import SETTINGS
from careweave.domain.models import Member

from . import catalogs as C
from .documents import DocumentGenerator, build_policy_corpus
from .simulate import JourneySimulator, SimOutput


def _dump(models: Iterable[BaseModel]) -> list[dict[str, Any]]:
    return [m.model_dump(mode="json") for m in models]


def _write_parquet(models: Iterable[BaseModel], path: Path) -> int:
    rows = _dump(models)
    df = pd.DataFrame(rows)
    # dict columns do not round-trip cleanly through parquet; JSON-encode them
    for col in df.columns:
        if len(df) and isinstance(df[col].iloc[0], dict):
            df[col] = df[col].map(json.dumps)
    df.to_parquet(path, index=False)
    return len(df)


def _write_jsonl(models: Iterable[BaseModel], path: Path) -> int:
    n = 0
    with path.open("w", encoding="utf-8") as fh:
        for m in models:
            fh.write(json.dumps(m.model_dump(mode="json")) + "\n")
            n += 1
    return n


def generate(n_members: int, seed: int, start: date, end: date) -> dict[str, int]:
    paths = SETTINGS.paths
    paths.ensure()
    rng = random.Random(seed)

    drugs = C.build_drugs()
    plans = C.build_plans()
    formulary = C.build_formulary(drugs, rng)
    pharmacies = C.build_pharmacies(rng)
    prescribers = C.build_prescribers(rng)

    sim = JourneySimulator(
        rng=rng, drugs=drugs, plans=plans, formulary=formulary,
        pharmacies=pharmacies, prescribers=prescribers, start=start, end=end,
    )
    out: SimOutput = sim.run(n_members)

    members_by_id: dict[str, Member] = {m.member_id: m for m in out.members}
    doc_gen = DocumentGenerator(
        rng, {d.drug_id: d for d in drugs}, {f.drug_id: f for f in formulary}
    )
    member_docs = doc_gen.generate(out, members_by_id)
    policy_docs = build_policy_corpus(plans)

    counts: dict[str, int] = {}
    s, d = paths.synthetic, paths.documents
    counts["drugs"] = _write_parquet(drugs, s / "drugs.parquet")
    counts["plans"] = _write_parquet(plans, s / "plans.parquet")
    counts["formulary"] = _write_parquet(formulary, s / "formulary.parquet")
    counts["pharmacies"] = _write_parquet(pharmacies, s / "pharmacies.parquet")
    counts["prescribers"] = _write_parquet(prescribers, s / "prescribers.parquet")
    counts["members"] = _write_parquet(out.members, s / "members.parquet")
    counts["prescriptions"] = _write_parquet(out.prescriptions, s / "prescriptions.parquet")
    counts["authorizations"] = _write_parquet(out.authorizations, s / "authorizations.parquet")
    counts["claims"] = _write_parquet(out.claims, s / "claims.parquet")
    counts["interactions"] = _write_parquet(out.interactions, s / "interactions.parquet")
    counts["events"] = _write_jsonl(out.events, s / "events.jsonl")
    counts["member_documents"] = _write_jsonl(member_docs, d / "member_documents.jsonl")
    counts["policy_documents"] = _write_jsonl(policy_docs, d / "policy_documents.jsonl")

    # Latent traits are written to a clearly quarantined file. tests/test_no_leakage.py
    # asserts that no column sourced from here ever reaches the feature builder.
    traits_path = s / "_latent_traits_DO_NOT_USE_AS_FEATURES.parquet"
    pd.DataFrame(
        [{"member_id": mid, **asdict(t)} for mid, t in out.traits.items()]
    ).to_parquet(traits_path, index=False)

    manifest = {
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "seed": seed,
        "n_members": n_members,
        "window": {"start": start.isoformat(), "end": end.isoformat()},
        "counts": counts,
        "notice": (
            "All data in this directory is synthetic and generated by "
            "careweave.data.generator. It contains no real people, no real "
            "medications, no real prices, and no real plan documents."
        ),
    }
    (s / "manifest.json").write_text(json.dumps(manifest, indent=2))
    return counts


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate the CareWeave synthetic ecosystem")
    ap.add_argument("--members", type=int, default=SETTINGS.generation.n_members)
    ap.add_argument("--seed", type=int, default=SETTINGS.generation.seed)
    args = ap.parse_args()

    start = date.fromisoformat(SETTINGS.generation.start_date)
    end = date.fromisoformat(SETTINGS.generation.end_date)
    counts = generate(args.members, args.seed, start, end)

    width = max(len(k) for k in counts)
    print(f"Generated synthetic ecosystem (seed={args.seed}, members={args.members})")
    for k, v in counts.items():
        print(f"  {k:<{width}}  {v:>8,}")
    print(f"\nWritten to {SETTINGS.paths.synthetic} and {SETTINGS.paths.documents}")


if __name__ == "__main__":
    main()
